language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Gradle 권한 부여
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ds0631@gmail.com

before_deploy:
  - zip -r firstspringboot *
  - mkdir -p deploy
  - mv firstspringboot.zip deploy/firstspringboot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_acces_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값

    bucket: firstspringboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_acces_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값

    bucket: firstspringboot-build # S3 버킷
    key: firstspringboot.zip # 빌드 파일을 압축해서 전달

    bundle_type: zip # 압축 확장자
    application: firstspringboot # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: firstspringboot-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notification:
  email:
    recipients:
      - ds0631@gmail.com